// lib/institution/charters/registry.ts
//
// Declarative registry of every sovereign ministry charter. Every claim
// in a charter (hasDesignSystem, shippedDomains, workflows, etc.) is
// asserted by the maturity test against the actual codebase so the
// registry cannot drift out of sync with reality.

import type { MinistryCharter } from './types';

export const CHARTERS: MinistryCharter[] = [
  // ── Reference tier ────────────────────────────────────────────────
  {
    id: 'ministry-interior',
    label: 'Ministry of the Interior',
    mount: { kind: 'archetype', archetype: 'INTERIOR' },
    blueprint: [
      { document: 'master', section: '10', title: 'National Identity & Citizen Graph' },
      { document: 'master', section: '18', title: 'Immigration & Borders' },
      { document: 'master', section: '19', title: 'National Security & Emergency Response' },
      { document: 'master', section: '39', title: 'Command & Control Centers' },
    ],
    grammar: 'situation-room',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Justice', 'Foreign Affairs', 'Cabinet'], consumes: ['Health', 'Energy', 'Transport', 'Emergency'], emitsCascade: true },
    expectedDomains: 50,
    shippedDomains: 68,
    workflows: [
      { id: 'civil-registry-issuance', title: 'Civil registry issuance', kind: 'permit' },
      { id: 'border-incident-escalation', title: 'Border incident escalation', kind: 'incident' },
      { id: 'anti-corruption-case', title: 'Anti-corruption case', kind: 'case' },
    ],
    safeguardsConstant: '',
    tags: ['command', 'security', 'continuity'],
  },
  {
    id: 'ministry-health',
    label: 'Ministry of Health',
    mount: { kind: 'archetype', archetype: 'HEALTH' },
    blueprint: [{ document: 'master', section: '13', title: 'Healthcare Infrastructure' }],
    grammar: 'clinical-floor-plan',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Emergency', 'Cabinet', 'Justice', 'Treasury'], consumes: ['Environment', 'Interior', 'Treasury', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'patient-admission', title: 'Patient admission', kind: 'case' },
      { id: 'break-glass-access', title: 'Break-glass emergency EHR access', kind: 'case' },
    ],
    safeguardsConstant: '',
    tags: ['service', 'continuity', 'social'],
  },
  {
    id: 'police-command',
    label: 'Police Command',
    mount: { kind: 'agency', appId: 'police-command' },
    blueprint: [{ document: 'master', section: '19', title: 'National Security & Emergency Response' }],
    grammar: 'situation-room',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Justice', 'Interior', 'Health', 'Cabinet'], consumes: ['Emergency', 'Interior', 'Justice'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'incident-dispatch', title: 'Incident dispatch', kind: 'incident' },
      { id: 'investigation-handoff', title: 'Investigation handoff to prosecutor', kind: 'case' },
      { id: 'use-of-force-review', title: 'Use-of-force mandatory review', kind: 'approval' },
    ],
    safeguardsConstant: 'POLICE_SAFEGUARDS',
    tags: ['security', 'command'],
  },
  {
    id: 'ministry-finance',
    label: 'Treasury & Finance',
    mount: { kind: 'archetype', archetype: 'FINANCE' },
    blueprint: [
      { document: 'master', section: '9', title: 'Treasury & Payment Infrastructure' },
      { document: 'master', section: '22', title: 'Taxation & Revenue Collection' },
    ],
    grammar: 'fiscal-ledger',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Cabinet', 'All ministries', 'Public Wallet', 'Foreign Affairs', 'National Coordination'], consumes: ['Customs', 'Trade & Industry', 'Justice', 'Labour'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'disbursement-authorisation', title: 'Disbursement authorisation', kind: 'approval' },
      { id: 'reserve-drawdown', title: 'Sovereign reserve drawdown', kind: 'procurement' },
    ],
    safeguardsConstant: '',
    tags: ['economy', 'continuity', 'command'],
  },
  // ── Advanced tier (this branch's work) ────────────────────────────
  {
    id: 'ministry-justice',
    label: 'Ministry of Justice & Constitutional Affairs',
    mount: { kind: 'archetype', archetype: 'JUSTICE' },
    blueprint: [{ document: 'master', section: '20', title: 'Digital Courts & Justice' }],
    grammar: 'docket-chamber',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Treasury', 'Cabinet', 'Legislature', 'National Coordination'], consumes: ['Police Command', 'Interior'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'case-filing-approval', title: 'Case filing approval', kind: 'case' },
      { id: 'evidence-chain-handoff', title: 'Evidence chain-of-custody handoff', kind: 'permit' },
    ],
    safeguardsConstant: 'JUSTICE_RECORDS_SAFEGUARDS',
    tags: ['command', 'continuity', 'service'],
  },
  {
    id: 'ministry-environment',
    label: 'Ministry of Environment & Climate Resilience',
    mount: { kind: 'archetype', archetype: 'ENVIRONMENT' },
    blueprint: [{ document: 'master', section: '25', title: 'Environment & Climate Intelligence' }],
    grammar: 'biome-map',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Agriculture', 'Health', 'Transport', 'Energy', 'Cabinet', 'Emergency', 'Justice'], consumes: ['Agriculture', 'Trade', 'Energy'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'environmental-impact-assessment', title: 'Environmental Impact Assessment', kind: 'approval' },
      { id: 'extraction-permit', title: 'Extraction permit', kind: 'permit' },
      { id: 'climate-incident-declaration', title: 'Climate incident declaration', kind: 'incident' },
    ],
    safeguardsConstant: 'CLIMATE_RESILIENCE_SAFEGUARDS',
    tags: ['continuity', 'environment'],
  },
  {
    id: 'ministry-agriculture',
    label: 'Ministry of Agriculture & Food Security',
    mount: { kind: 'archetype', archetype: 'AGRICULTURE' },
    blueprint: [{ document: 'master', section: '17', title: 'Agriculture & Food Security' }],
    grammar: 'seasonal-wheel',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Treasury', 'Trade', 'Environment', 'Cabinet', 'Health', 'Emergency'], consumes: ['Environment', 'Transport', 'Energy'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'seed-subsidy-disbursement', title: 'Seed subsidy disbursement', kind: 'procurement' },
      { id: 'pest-response', title: 'Pest outbreak response', kind: 'incident' },
      { id: 'irrigation-allocation', title: 'Irrigation allocation', kind: 'permit' },
    ],
    safeguardsConstant: 'AGRICULTURE_RURAL_SAFEGUARDS',
    tags: ['continuity', 'economy', 'social'],
  },
  {
    id: 'ministry-energy',
    label: 'Ministry of Energy',
    mount: { kind: 'archetype', archetype: 'ENERGY' },
    blueprint: [{ document: 'master', section: '21', title: 'Public Works & Infrastructure Management' }],
    grammar: 'one-line-diagram',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Health', 'Transport', 'Trade', 'Treasury', 'Environment', 'Cabinet', 'Emergency'], consumes: ['Environment', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'blackout-restoration', title: 'Blackout restoration', kind: 'incident' },
      { id: 'generation-dispatch', title: 'Generation dispatch', kind: 'approval' },
      { id: 'renewable-grid-connection', title: 'Renewable grid connection', kind: 'permit' },
    ],
    safeguardsConstant: 'ENERGY_EXTENDED_SAFEGUARDS',
    tags: ['continuity', 'economy', 'command'],
  },
  {
    id: 'ministry-transport',
    label: 'Ministry of Transport & National Logistics',
    mount: { kind: 'archetype', archetype: 'TRANSPORT' },
    blueprint: [{ document: 'master', section: '16', title: 'Transport & Mobility' }],
    grammar: 'corridor-map',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Trade', 'Treasury', 'Emergency', 'Cabinet', 'Health', 'Agriculture'], consumes: ['Energy', 'Environment', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'infrastructure-closure', title: 'Infrastructure closure', kind: 'incident' },
      { id: 'evacuation-routing', title: 'Evacuation routing', kind: 'incident' },
      { id: 'freight-permit', title: 'Freight permit', kind: 'permit' },
    ],
    safeguardsConstant: 'TRANSPORT_EXTENDED_SAFEGUARDS',
    tags: ['continuity', 'economy'],
  },
  {
    id: 'ministry-labor',
    label: 'Ministry of Labour & Social Protection',
    mount: { kind: 'archetype', archetype: 'LABOR' },
    blueprint: [
      { document: 'master', section: '23', title: 'Welfare & Social Benefits' },
      { document: 'master', section: '24', title: 'Labor & Employment' },
    ],
    grammar: 'workforce-flow',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Treasury', 'Trade', 'Health', 'Cabinet', 'Justice', 'Emergency'], consumes: ['Education', 'Trade', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'unemployment-benefit-disbursement', title: 'Unemployment benefit disbursement', kind: 'procurement' },
      { id: 'workplace-inspection', title: 'Workplace inspection', kind: 'case' },
      { id: 'industrial-tribunal', title: 'Industrial tribunal hearing', kind: 'case' },
    ],
    safeguardsConstant: 'LABOUR_EXTENDED_SAFEGUARDS',
    tags: ['social', 'continuity'],
  },
  {
    id: 'ministry-trade',
    label: 'Ministry of Trade, Industry & Strategic Production',
    mount: { kind: 'archetype', archetype: 'TRADE' },
    blueprint: [{ document: 'master', section: '21', title: 'Public Works & Infrastructure Management' }],
    grammar: 'industrial-corridor',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Treasury', 'Transport', 'Energy', 'Foreign Affairs', 'Cabinet', 'Labour'], consumes: ['Energy', 'Transport', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'export-licence', title: 'Export licence', kind: 'permit' },
      { id: 'industrial-incident-response', title: 'Industrial incident response', kind: 'incident' },
      { id: 'trade-agreement-ratification', title: 'Trade agreement ratification', kind: 'approval' },
    ],
    safeguardsConstant: 'INDUSTRIAL_CONTINUITY_SAFEGUARDS',
    tags: ['economy', 'continuity'],
  },
  {
    id: 'ministry-education',
    label: 'Ministry of Education',
    mount: { kind: 'archetype', archetype: 'EDUCATION' },
    blueprint: [{ document: 'master', section: '14', title: 'Education Infrastructure' }],
    grammar: 'lecture-hall',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Labour', 'Cabinet', 'Health', 'Trade', 'Emergency', 'Justice'], consumes: ['Treasury', 'Foreign Affairs', 'Communications'], emitsCascade: true },
    expectedDomains: 35,
    shippedDomains: 35,
    workflows: [
      { id: 'curriculum-review', title: 'Curriculum review', kind: 'approval' },
      { id: 'exam-integrity-response', title: 'Examination integrity response', kind: 'incident' },
      { id: 'research-grant', title: 'Research grant award', kind: 'approval' },
    ],
    safeguardsConstant: 'KNOWLEDGE_SAFEGUARDS',
    tags: ['social', 'continuity'],
  },
  // ── Standing agencies ─────────────────────────────────────────────
  {
    id: 'foreign-affairs',
    label: 'Foreign Affairs & Geopolitical Relations',
    mount: { kind: 'agency', appId: 'foreign-affairs' },
    blueprint: [{ document: 'master', section: '4', title: 'Global Positioning' }],
    grammar: 'world-dispatch',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Treasury', 'Trade', 'Interior', 'Energy', 'Cabinet', 'Justice', 'Defense'], consumes: ['Trade', 'Agriculture'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'treaty-ratification', title: 'Treaty ratification', kind: 'approval' },
      { id: 'demarche-delivery', title: 'Diplomatic démarche delivery', kind: 'incident' },
      { id: 'consular-evacuation', title: 'Consular evacuation', kind: 'case' },
    ],
    safeguardsConstant: 'FOREIGN_EXTENDED_SAFEGUARDS',
    tags: ['command', 'continuity'],
  },
  {
    id: 'emergency-response',
    label: 'Emergency Management & National Resilience',
    mount: { kind: 'agency', appId: 'emergency-response' },
    blueprint: [{ document: 'master', section: '19', title: 'National Security & Emergency Response' }],
    grammar: 'crisis-theatre',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Health', 'Cabinet', 'Treasury', 'Communications', 'Justice'], consumes: ['Environment', 'Energy', 'Transport'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'incident-activation', title: 'Incident activation', kind: 'incident' },
      { id: 'evacuation-order', title: 'Evacuation order', kind: 'approval' },
      { id: 'resource-mobilisation', title: 'Resource mobilisation', kind: 'procurement' },
    ],
    safeguardsConstant: 'EMERGENCY_SAFEGUARDS',
    tags: ['command', 'security', 'continuity'],
  },
  {
    id: 'communications',
    label: 'Communications & Digital Infrastructure',
    mount: { kind: 'agency', appId: 'communications' },
    blueprint: [
      { document: 'master', section: '30', title: 'Cybersecurity Architecture' },
      { document: 'master', section: '37', title: 'Public Communications System' },
      { document: 'master', section: '46', title: 'National Notification Infrastructure' },
    ],
    grammar: 'topology-graph',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Treasury', 'Justice', 'Energy', 'Cabinet', 'Emergency', 'Foreign Affairs'], consumes: ['Energy', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'cyber-incident-response', title: 'Cyber incident response', kind: 'incident' },
      { id: 'emergency-broadcast', title: 'Emergency broadcast', kind: 'incident' },
      { id: 'spectrum-licence', title: 'Spectrum licence award', kind: 'permit' },
    ],
    safeguardsConstant: 'COMMUNICATIONS_SAFEGUARDS',
    tags: ['continuity', 'security', 'service'],
  },
  // ── Constitutional branches ──────────────────────────────────────
  {
    id: 'senate',
    label: 'Senate (Upper House)',
    mount: { kind: 'agency', appId: 'senate' },
    blueprint: [{ document: 'master', section: '6', title: 'Sovereign Legislature — Upper Chamber' }],
    grammar: 'senate-chamber',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['National Assembly', 'Cabinet', 'Judicial Branch', 'Foreign Affairs', 'Treasury', 'Justice'], consumes: ['National Assembly', 'Cabinet', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'treaty-ratification', title: 'Treaty ratification (Senate concurrence)', kind: 'approval' },
      { id: 'committee-inquiry', title: 'Senate committee inquiry', kind: 'case' },
      { id: 'senate-bill-review', title: 'Senate bill review (second reading)', kind: 'approval' },
    ],
    safeguardsConstant: 'SENATE_SAFEGUARDS',
    tags: ['command', 'continuity', 'service'],
  },
  {
    id: 'assembly',
    label: 'National Assembly (Lower House)',
    mount: { kind: 'agency', appId: 'assembly' },
    blueprint: [{ document: 'master', section: '7', title: 'Sovereign Legislature — Lower Chamber' }],
    grammar: 'assembly-floor',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Senate', 'Cabinet', 'Treasury', 'Judicial Branch', 'Justice', 'Police Command'], consumes: ['Senate', 'Cabinet', 'Treasury'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'budget-appropriation', title: 'Budget appropriation', kind: 'procurement' },
      { id: 'citizen-petition-debate', title: 'Citizen petition debate (5,000-threshold)', kind: 'case' },
      { id: 'question-time', title: 'Question Time (weekly)', kind: 'case' },
    ],
    safeguardsConstant: 'ASSEMBLY_SAFEGUARDS',
    tags: ['command', 'continuity', 'service'],
  },
  {
    id: 'presidency',
    label: 'Presidency · Cabinet Office',
    mount: { kind: 'agency', appId: 'presidency' },
    blueprint: [{ document: 'master', section: '2', title: 'Executive Branch — Presidency & Cabinet' }],
    grammar: 'executive-mansion',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Cabinet (15 ministries)', 'Senate', 'National Assembly', 'Judicial Branch', 'Foreign Affairs', 'Audit Vault'], consumes: ['Cabinet', 'Senate', 'National Assembly', 'Judicial Branch', 'Emergency Response', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'executive-order', title: 'Executive order issuance', kind: 'approval' },
      { id: 'cabinet-resolution', title: 'Cabinet resolution adoption', kind: 'approval' },
      { id: 'ministerial-appointment', title: 'Ministerial appointment (Senate concurrence)', kind: 'approval' },
    ],
    safeguardsConstant: 'PRESIDENTIAL_SAFEGUARDS',
    tags: ['command', 'continuity', 'service'],
  },
  {
    id: 'citizen-portal',
    label: 'Citizen Super-Portal',
    mount: { kind: 'agency', appId: 'citizen-portal' },
    blueprint: [{ document: 'master', section: '11', title: 'Citizen Super-Portal — Unified Wallet' }],
    grammar: 'citizen-wallet',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Treasury', 'Health', 'Justice', 'Assembly', 'Labour', 'Foreign Affairs'], consumes: ['All ministries', 'Interior', 'Health', 'Education', 'Assembly'], emitsCascade: true },
    expectedDomains: 33,
    shippedDomains: 33,
    workflows: [
      { id: 'service-request', title: 'Citizen service request', kind: 'case' },
      { id: 'consent-grant', title: 'Cross-ministry consent grant', kind: 'approval' },
      { id: 'appeal-filing', title: 'Universal right of appeal', kind: 'case' },
    ],
    safeguardsConstant: 'CITIZEN_PORTAL_SAFEGUARDS',
    tags: ['service', 'social', 'continuity'],
  },
  {
    id: 'noc',
    label: 'National Operations Centre',
    mount: { kind: 'agency', appId: 'noc' },
    blueprint: [{ document: 'master', section: '12', title: 'National Operations Centre' }],
    grammar: 'national-ops-room',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Presidency / Cabinet', 'Emergency Response', 'Communications', 'Audit Vault'], consumes: ['All 15 ministries', 'Police Command', 'Emergency Response', 'Communications', 'Foreign Affairs', 'Senate · Assembly'], emitsCascade: true },
    expectedDomains: 26,
    shippedDomains: 26,
    workflows: [
      { id: 'cross-ministry-coordination', title: 'Cross-ministry coordination decision', kind: 'approval' },
      { id: 'incident-fusion', title: 'National incident fusion', kind: 'incident' },
      { id: 'public-briefing', title: 'NOC public briefing cycle', kind: 'case' },
    ],
    safeguardsConstant: 'NOC_SAFEGUARDS',
    tags: ['command', 'continuity', 'security'],
  },
  {
    id: 'judicial-branch',
    label: 'Judicial Branch',
    mount: { kind: 'agency', appId: 'judiciary' },
    blueprint: [{ document: 'master', section: '8', title: 'Sovereign Judicial Branch' }],
    grammar: 'apex-court',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Senate', 'National Assembly', 'Cabinet', 'Justice', 'Police Command', 'Audit Vault'], consumes: ['Senate', 'National Assembly', 'Justice'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'constitutional-ruling', title: 'Constitutional ruling', kind: 'case' },
      { id: 'judicial-conduct-review', title: 'Judicial conduct review', kind: 'case' },
      { id: 'appellate-hearing', title: 'Appellate hearing', kind: 'case' },
    ],
    safeguardsConstant: 'JUDICIAL_BRANCH_SAFEGUARDS',
    tags: ['command', 'continuity', 'service'],
  },
];

export function chartersById(): Map<string, MinistryCharter> {
  return new Map(CHARTERS.map(c => [c.id, c]));
}
