// lib/institution/charters/registry.ts
//
// Declarative registry of every sovereign ministry charter. Every claim
// in a charter (hasDesignSystem, shippedDomains, workflows, etc.) is
// asserted by the maturity test against the actual codebase so the
// registry cannot drift out of sync with reality.

import type { MinistryCharter } from './types';

export const CHARTERS: MinistryCharter[] = [
  // ── Reference tier ────────────────────────────────────────────────
  {
    id: 'ministry-interior',
    label: 'Ministry of the Interior',
    mount: { kind: 'archetype', archetype: 'INTERIOR' },
    blueprint: [
      { document: 'master', section: '10', title: 'National Identity & Citizen Graph' },
      { document: 'master', section: '18', title: 'Immigration & Borders' },
      { document: 'master', section: '19', title: 'National Security & Emergency Response' },
      { document: 'master', section: '39', title: 'Command & Control Centers' },
    ],
    grammar: 'situation-room',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Justice', 'Foreign Affairs', 'Cabinet'], consumes: ['Health', 'Energy', 'Transport', 'Emergency'], emitsCascade: true },
    expectedDomains: 50,
    shippedDomains: 68,
    workflows: [
      { id: 'civil-registry-issuance', title: 'Civil registry issuance', kind: 'permit' },
      { id: 'border-incident-escalation', title: 'Border incident escalation', kind: 'incident' },
      { id: 'anti-corruption-case', title: 'Anti-corruption case', kind: 'case' },
    ],
    safeguardsConstant: '',
    tags: ['command', 'security', 'continuity'],
  },
  {
    id: 'ministry-health',
    label: 'Ministry of Health',
    mount: { kind: 'archetype', archetype: 'HEALTH' },
    blueprint: [{ document: 'master', section: '13', title: 'Healthcare Infrastructure' }],
    grammar: 'clinical-floor-plan',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Emergency', 'Cabinet', 'Justice', 'Treasury'], consumes: ['Environment', 'Interior', 'Treasury', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'patient-admission', title: 'Patient admission', kind: 'case' },
      { id: 'break-glass-access', title: 'Break-glass emergency EHR access', kind: 'case' },
    ],
    safeguardsConstant: '',
    tags: ['service', 'continuity', 'social'],
  },
  {
    id: 'police-command',
    label: 'Police Command',
    mount: { kind: 'agency', appId: 'police-command' },
    blueprint: [{ document: 'master', section: '19', title: 'National Security & Emergency Response' }],
    grammar: 'situation-room',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Justice', 'Interior', 'Health', 'Cabinet'], consumes: ['Emergency', 'Interior', 'Justice'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'incident-dispatch', title: 'Incident dispatch', kind: 'incident' },
      { id: 'investigation-handoff', title: 'Investigation handoff to prosecutor', kind: 'case' },
      { id: 'use-of-force-review', title: 'Use-of-force mandatory review', kind: 'approval' },
    ],
    safeguardsConstant: 'POLICE_SAFEGUARDS',
    tags: ['security', 'command'],
  },
  {
    id: 'ministry-finance',
    label: 'Treasury & Finance',
    mount: { kind: 'archetype', archetype: 'FINANCE' },
    blueprint: [
      { document: 'master', section: '9', title: 'Treasury & Payment Infrastructure' },
      { document: 'master', section: '22', title: 'Taxation & Revenue Collection' },
    ],
    grammar: 'fiscal-ledger',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Cabinet', 'All ministries', 'Public Wallet', 'Foreign Affairs', 'National Coordination'], consumes: ['Customs', 'Trade & Industry', 'Justice', 'Labour'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'disbursement-authorisation', title: 'Disbursement authorisation', kind: 'approval' },
      { id: 'reserve-drawdown', title: 'Sovereign reserve drawdown', kind: 'procurement' },
    ],
    safeguardsConstant: '',
    tags: ['economy', 'continuity', 'command'],
  },
  // ── Advanced tier (this branch's work) ────────────────────────────
  {
    id: 'ministry-justice',
    label: 'Ministry of Justice & Constitutional Affairs',
    mount: { kind: 'archetype', archetype: 'JUSTICE' },
    blueprint: [{ document: 'master', section: '20', title: 'Digital Courts & Justice' }],
    grammar: 'docket-chamber',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Treasury', 'Cabinet', 'Legislature', 'National Coordination'], consumes: ['Police Command', 'Interior'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'case-filing-approval', title: 'Case filing approval', kind: 'case' },
      { id: 'evidence-chain-handoff', title: 'Evidence chain-of-custody handoff', kind: 'permit' },
    ],
    safeguardsConstant: 'JUSTICE_RECORDS_SAFEGUARDS',
    tags: ['command', 'continuity', 'service'],
  },
  {
    id: 'ministry-environment',
    label: 'Ministry of Environment & Climate Resilience',
    mount: { kind: 'archetype', archetype: 'ENVIRONMENT' },
    blueprint: [{ document: 'master', section: '25', title: 'Environment & Climate Intelligence' }],
    grammar: 'biome-map',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Agriculture', 'Health', 'Transport', 'Energy', 'Cabinet', 'Emergency', 'Justice'], consumes: ['Agriculture', 'Trade', 'Energy'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'environmental-impact-assessment', title: 'Environmental Impact Assessment', kind: 'approval' },
      { id: 'extraction-permit', title: 'Extraction permit', kind: 'permit' },
      { id: 'climate-incident-declaration', title: 'Climate incident declaration', kind: 'incident' },
    ],
    safeguardsConstant: 'CLIMATE_RESILIENCE_SAFEGUARDS',
    tags: ['continuity', 'environment'],
  },
  {
    id: 'ministry-agriculture',
    label: 'Ministry of Agriculture & Food Security',
    mount: { kind: 'archetype', archetype: 'AGRICULTURE' },
    blueprint: [{ document: 'master', section: '17', title: 'Agriculture & Food Security' }],
    grammar: 'seasonal-wheel',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Treasury', 'Trade', 'Environment', 'Cabinet', 'Health', 'Emergency'], consumes: ['Environment', 'Transport', 'Energy'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'seed-subsidy-disbursement', title: 'Seed subsidy disbursement', kind: 'procurement' },
      { id: 'pest-response', title: 'Pest outbreak response', kind: 'incident' },
      { id: 'irrigation-allocation', title: 'Irrigation allocation', kind: 'permit' },
    ],
    safeguardsConstant: 'AGRICULTURE_RURAL_SAFEGUARDS',
    tags: ['continuity', 'economy', 'social'],
  },
  {
    id: 'ministry-energy',
    label: 'Ministry of Energy',
    mount: { kind: 'archetype', archetype: 'ENERGY' },
    blueprint: [{ document: 'master', section: '21', title: 'Public Works & Infrastructure Management' }],
    grammar: 'one-line-diagram',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Health', 'Transport', 'Trade', 'Treasury', 'Environment', 'Cabinet', 'Emergency'], consumes: ['Environment', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'blackout-restoration', title: 'Blackout restoration', kind: 'incident' },
      { id: 'generation-dispatch', title: 'Generation dispatch', kind: 'approval' },
      { id: 'renewable-grid-connection', title: 'Renewable grid connection', kind: 'permit' },
    ],
    safeguardsConstant: 'ENERGY_EXTENDED_SAFEGUARDS',
    tags: ['continuity', 'economy', 'command'],
  },
  {
    id: 'ministry-transport',
    label: 'Ministry of Transport & National Logistics',
    mount: { kind: 'archetype', archetype: 'TRANSPORT' },
    blueprint: [{ document: 'master', section: '16', title: 'Transport & Mobility' }],
    grammar: 'corridor-map',
    hasDesignSystem: false,
    hasShell: false,
    federation: { produces: ['Trade', 'Treasury', 'Emergency', 'Cabinet'], consumes: ['Energy', 'Environment'], emitsCascade: true },
    expectedDomains: 25,
    shippedDomains: 7,
    workflows: [],
    safeguardsConstant: 'TRANSPORT_EXTENDED_SAFEGUARDS',
    tags: ['continuity', 'economy'],
  },
  {
    id: 'ministry-labor',
    label: 'Ministry of Labour & Social Protection',
    mount: { kind: 'archetype', archetype: 'LABOR' },
    blueprint: [
      { document: 'master', section: '23', title: 'Welfare & Social Benefits' },
      { document: 'master', section: '24', title: 'Labor & Employment' },
    ],
    grammar: 'workforce-flow',
    hasDesignSystem: false,
    hasShell: false,
    federation: { produces: ['Treasury', 'Trade', 'Health', 'Cabinet'], consumes: ['Education', 'Trade'], emitsCascade: true },
    expectedDomains: 25,
    shippedDomains: 7,
    workflows: [],
    safeguardsConstant: 'LABOUR_EXTENDED_SAFEGUARDS',
    tags: ['social', 'continuity'],
  },
  {
    id: 'ministry-trade',
    label: 'Ministry of Trade, Industry & Strategic Production',
    mount: { kind: 'archetype', archetype: 'TRADE' },
    blueprint: [{ document: 'master', section: '21', title: 'Public Works & Infrastructure Management' }],
    grammar: 'industrial-corridor',
    hasDesignSystem: false,
    hasShell: false,
    federation: { produces: ['Treasury', 'Transport', 'Energy', 'Foreign Affairs', 'Cabinet'], consumes: ['Energy', 'Transport', 'Foreign Affairs'], emitsCascade: true },
    expectedDomains: 25,
    shippedDomains: 4,
    workflows: [],
    safeguardsConstant: '',
    tags: ['economy', 'continuity'],
  },
  {
    id: 'ministry-education',
    label: 'Ministry of Education',
    mount: { kind: 'archetype', archetype: 'EDUCATION' },
    blueprint: [{ document: 'master', section: '14', title: 'Education Infrastructure' }],
    grammar: 'lecture-hall',
    hasDesignSystem: false,
    hasShell: false,
    federation: { produces: ['Labour', 'Cabinet'], consumes: ['Treasury'], emitsCascade: true },
    expectedDomains: 25,
    shippedDomains: 4,
    workflows: [],
    safeguardsConstant: '',
    tags: ['social', 'continuity'],
  },
  // ── Standing agencies ─────────────────────────────────────────────
  {
    id: 'foreign-affairs',
    label: 'Foreign Affairs & Geopolitical Relations',
    mount: { kind: 'agency', appId: 'foreign-affairs' },
    blueprint: [{ document: 'master', section: '4', title: 'Global Positioning' }],
    grammar: 'world-dispatch',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Treasury', 'Trade', 'Interior', 'Energy', 'Cabinet', 'Justice', 'Defense'], consumes: ['Trade', 'Agriculture'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'treaty-ratification', title: 'Treaty ratification', kind: 'approval' },
      { id: 'demarche-delivery', title: 'Diplomatic démarche delivery', kind: 'incident' },
      { id: 'consular-evacuation', title: 'Consular evacuation', kind: 'case' },
    ],
    safeguardsConstant: 'FOREIGN_EXTENDED_SAFEGUARDS',
    tags: ['command', 'continuity'],
  },
  {
    id: 'emergency-response',
    label: 'Emergency Management & National Resilience',
    mount: { kind: 'agency', appId: 'emergency-response' },
    blueprint: [{ document: 'master', section: '19', title: 'National Security & Emergency Response' }],
    grammar: 'crisis-theatre',
    hasDesignSystem: true,
    hasShell: true,
    federation: { produces: ['Interior', 'Health', 'Cabinet', 'Treasury', 'Communications', 'Justice'], consumes: ['Environment', 'Energy', 'Transport'], emitsCascade: true },
    expectedDomains: 30,
    shippedDomains: 30,
    workflows: [
      { id: 'incident-activation', title: 'Incident activation', kind: 'incident' },
      { id: 'evacuation-order', title: 'Evacuation order', kind: 'approval' },
      { id: 'resource-mobilisation', title: 'Resource mobilisation', kind: 'procurement' },
    ],
    safeguardsConstant: 'EMERGENCY_SAFEGUARDS',
    tags: ['command', 'security', 'continuity'],
  },
  {
    id: 'communications',
    label: 'Communications & Digital Infrastructure',
    mount: { kind: 'agency', appId: 'communications' },
    blueprint: [
      { document: 'master', section: '30', title: 'Cybersecurity Architecture' },
      { document: 'master', section: '37', title: 'Public Communications System' },
      { document: 'master', section: '46', title: 'National Notification Infrastructure' },
    ],
    grammar: 'topology-graph',
    hasDesignSystem: false,
    hasShell: false,
    federation: { produces: ['Interior', 'Treasury', 'Justice', 'Energy', 'Cabinet'], consumes: [], emitsCascade: true },
    expectedDomains: 25,
    shippedDomains: 4,
    workflows: [],
    safeguardsConstant: 'COMMUNICATIONS_SAFEGUARDS',
    tags: ['continuity', 'security', 'service'],
  },
];

export function chartersById(): Map<string, MinistryCharter> {
  return new Map(CHARTERS.map(c => [c.id, c]));
}
